name: bouncy_effect
description: A widget that adds a bouncy scale animation effect to its child when tapped.
version: 1.0.5
homepage: https://github.com/possible3656/bouncy_effect
repository: https://github.com/possible3656/bouncy_effect
issue_tracker: https://github.com/possible3656/bouncy_effect/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
